
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('timeline').del()
    .then(function () {
      // Inserts seed entries
      return knex('timeline').insert([
        {date: '1840', country: 'New Zealand', title: 'Signature of the Waitangi treaty', event: 'New Zealand founding document is signed by over 500 Maori chiefs and British Crown representatives. It is celebrated each year in New Zealand on the 6th of February.', source: 'https://nzhistory.govt.nz/politics/treaty/waitangi-day' },
        {date: '52BCE', country: 'France', title: 'The Siege and Battle of Alésia', event: 'Gaul (which approximately corresponds to today’s France, Belgium, Luxembourg, Switzerland , Italy and Germany) was mainly under the dominance of Rome. Gallic forces led by Vercingetorix rebelled. Alesia became held by his men and was strongly defended. With natural fortifications and fort plus the estimated 80,000 men inside the walls, Julius Caesar saw a siege as the only way to win against Vercingetorix. Caesar won after starving most fighters and civilian inside the city.', source: 'https://www.britannica.com/event/Battle-of-Alesia-52-BCE' },
        {date: '1789', country: 'France', title: 'The French Revolution', event : 'On the 14th July, the Bastille is assieged and surrender.', source: '' },
        {date: '1793', country: 'France',  title: 'Execution of Louis XVI', event: 'On the 21st January, ', source: '' },
        {date: '1769 ', country: 'New Zealand',  title: 'James Cook reaches the coastline of New Zealand and map it', event: `James Cook is a key figure in the history of New Zealand. On his first voyage he mapped the outline of the country’s coast so thoroughly and accurately that all the remaining voyages of discovery, including his own second and third voyages, had merely to fill in the detail and correct minor errors. Cook discovered New Zealand in more than a geographical sense. Having spent a total of 328 days on the coast, he and those with him left a vivid and comprehensive visual and written record of the country’s natural history. Few lands newly discovered by Europeans have been so comprehensively documented. A line can be drawn from Cook’s first voyage to the Treaty of Waitangi. In his instructions to Cook, the Earl of Morton, president of the Royal Society, stated that any "natives" he encountered were to be regarded as "the natural, and … legal possessors of the several Regions they inhabit"’", and that their voluntary consent would be needed before any of their lands were occupied by Europeans.`, source: 'https://teara.govt.nz/en/european-discovery-of-new-zealand/page-6' },
        {date: '1642', country: 'New Zealand',  title: 'Abel Tasman is the first European to see New Zealand', event: 'On 13 December 1642 the Dutch sighted ‘a large land, uplifted high’ – probably the Southern Alps. After sighting land, Tasman’s ships veered south, then turned north to pass Cape Foulwind and Cape Farewell. He sailed around Farewell Spit into what is now called Golden Bay, where he anchored on 18 and 19 December. Abel Tasman men got into trouble with men of the Ngāti Tūmatakōkiri Maori tribe as they landed, and responded by shooting one of their man.', source: 'https://teara.govt.nz/en/european-discovery-of-new-zealand/page-2' },
        {date: '481', country: 'France',  title: 'Clovis Unites the Franks ', event: 'The Franks moved into Gaul during the later Roman Empire. Clovis inherited the kingship of the Salian Franks in the late fifth century, a kingdom based in northeast France and Belgium. By his death this kingdom had spread south and west over much of France, incorporating the rest of the Franks. His dynasty, the Merovingians, would rule the region for the next two centuries. Clovis selected Paris as his capital and is sometimes regarded as the founder of France.', source: 'https://www.ancient.eu/Clovis_I/'  }
      ]);
    });
};
